### ISSUE TITLE
FixEncryptedVersionTest.php is spamming the drone CI log

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#151]
If I delete `FixEncryptedVersionTest.php` then the `phpunit` output is clean.
But with `FixEncryptedVersionTest.php` the output has a few thousand lines of "crud".

Can we redirect that output somewhere else? Or?

**Comment by phil-davis** [comment]
@sharidas do you know why various file content... is spewed out when running these unit tests?

**Comment by sharidas** [comment]
@phil-davis This is there in my radar and please keep this issue opened. I would like this issue to be pulled into one of the sprint. The root cause is, due to the use of an api `readFilePart` method in the command. To be specific https://github.com/owncloud/core/blob/master/lib/private/Files/View.php#L490 is causing the content to be spitted into console or so.

**Comment by phil-davis** [comment]
@sharidas does that line do anything useful?
or is it just 5 minutes to delete it and make a PR?

**Comment by chscherrer** [comment]
Has this log-spamming something to do with the fact, that FixEncryptedVersionTest.php consuming high amount of memory when having several TB / over 2 Mio files within the installation?

**Comment by karakayasemi** [comment]
fixed with #226
