### ISSUE TITLE
Encryption command `encryption:select-encryption-type` is not defined

### ISSUE THREAD

**Issue by saw-jan** [owncloud/encryption#393]
Encryption app fails to select the encryption type.

```bash
$ php occ encryption:enable
Encryption enabled

Default module: OC_DEFAULT_MODULE

$ php occ encryption:select-encryption-type masterkey --yes

                                                               
  Command "encryption:select-encryption-type" is not defined.  
                                                               
  Did you mean one of these?                                   
      encryption:change-key-storage-root                       
      encryption:decrypt-all                                   
      encryption:disable                                       
      encryption:enable                                        
      encryption:encrypt-all                                   
      encryption:fix-encrypted-version                         
      encryption:hsmdaemon                                     
      encryption:hsmdaemon:decrypt                             
      encryption:list-modules                                  
      encryption:migrate                                       
      encryption:recreate-master-key                           
      encryption:set-default-module                            
      encryption:show-key-storage-root                         
      encryption:status
```

From nightlies: https://drone.owncloud.com/owncloud/twofactor_totp/2148/19/11

**Comment by saw-jan** [comment]
CC @phil-davis @jnweiger

**Comment by phil-davis** [comment]
@saw-jan that command has been dropped in PR #389 - new installations can now only use master-key encryption, and so that happens automagically, there is no need for selection of the encryption type.

@DeepDiver1975 removed various references to that command from encryption app CI. And just today removed references in core - see PR https://github.com/owncloud/core/pull/40712

If there are any references left then please make PRs in the relevant repos. For example, there might be other apps that run test pipelines with encryption enabled (as well as the app itself enabled). We should notice those as failures in nightly CI.

**Comment by DeepDiver1975** [comment]
There is user ldap where I am working on right now.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/user_ldap/pull/779

**Comment by saw-jan** [comment]
Remaining apps:
`twofactor_totp`:
`ransomware_protection`:

**Comment by saw-jan** [comment]
> [owncloud/user_ldap#779](https://github.com/owncloud/user_ldap/pull/779)

The command runs in [nightly](https://drone.owncloud.com/owncloud/user_ldap/4450/151/17) but how?
```bash
+ php occ encryption:select-encryption-type masterkey --yes
Master key successfully enabled.
```

**Comment by phil-davis** [comment]
> > [owncloud/user_ldap#779](https://github.com/owncloud/user_ldap/pull/779)
> 
> The command runs in [nightly](https://drone.owncloud.com/owncloud/user_ldap/4450/151/17) but how? using old version? but it clones from the github
> 
> ```shell
> + php occ encryption:select-encryption-type masterkey --yes
> Master key successfully enabled.
> ```

That pipeline is running with core `latest` which is the official 10.12.0 release. `select-encryption-type` core code still exists in 10.12.0.

And we probably have to leave that command in there for that pipeline for now, because without it the encryption will not be set up, or might default to user-key.

When 10.12.1 is released and becomes `latest` then we will need to remove the `select-encryption-type` command from that CI.

Note: we want to test encryption against `latest` because we want to know that the app code will still run against the current `latest` core release. (If the app will no longer run against the `latest` core release, then that reminds us to set core min-version for the app etc.)

**Comment by saw-jan** [comment]
Ahhh, the change is in core. I thought the changes was made in encryption app. :+1:

**Comment by SwikritiT** [comment]
the command has been removed from CI now. Closing this as done.
