### ISSUE TITLE
Disable encryption - > no cleanup.

### ISSUE THREAD

**Issue by voroyam** [owncloud/encryption#56]
When disabling encryption with:

```
occ encryption:disable
occ app:disable encryption
```

The command

`occ encryption:status`

still returns

```
occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```

and the web UI shows:

![image](https://user-images.githubusercontent.com/24212810/45958117-e34ba880-c016-11e8-81da-085ae4cefef6.png)

Tested with 10.0.10 and master key encryption.

### Steps to reproduce:
- setup a new 10.0.10 ownCloud.
- Then enable master key encryption according to the [manual ](https://doc.owncloud.com/server/10.0/admin_manual/configuration/files/encryption_configuration_quick_guide.html?highlight=encryption#activation)

Commands:

```
occ maintenance:singleuser --on
occ app:enable encryption
occ encryption:enable
occ encryption:select-encryption-type masterkey -y
```

```
occ encryption:disable
# ignore the "already disabled" message
occ app:disable encryption
```

`occ encryption:status
`

### Expected result

  - enabled: **false**
  - defaultModule: OC_DEFAULT_MODULE

## Actual result

  - enabled: **true**
  - defaultModule: OC_DEFAULT_MODULE

**Comment by sharidas** [comment]
The problem here is with the cleaning up of the flags. For example this is how the state of appconfig when queried for encryption looks like ( which is causing the issue ):
![appconfig_encryption](https://user-images.githubusercontent.com/3600427/46144194-d67abf00-c279-11e8-8f47-3c9c7bd29607.png)

As a quick test when I changed the `useMasterKey` value to `0`, the issue is not seen in the UI. 

We need to clean up the flags when the encryption is disabled followed by encryption app disable. Also we need to verify the keys created in the data folder or `datadirectory` to be cleaned up when user disables the encryption app.

**Comment by butonic** [comment]
maybe related: https://github.com/owncloud/core/issues/29297
